sudo: false
language: erlang
install: true
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- chmod +x rebar3
env: PATH=$PATH:.
cache:
  directories:
  - $HOME/.cache/rebar3/
otp_release:
- 19.3
- 19.0
- 18.3
- 18.0
script:
- rebar3 as test do xref, dialyzer, eunit
- rebar3 as test coveralls send
